### ISSUE TITLE
Please Build and Image

### ISSUE THREAD

**Issue by Vladik01-11** [Viet200103/Notification-History-Android#1]
When can I expect a build and is it possible to save images from notifications?

**Comment by Viet200103** [comment]
Notisave can get images from notifications if the notifications allow image retrieval, like notification picture style

**Comment by Vladik01-11** [comment]
This is great (I guess I just don't understand notification types), can you make a release or create a workflows file that will send the apk to actions

**Comment by Viet200103** [comment]
I built a release apk, you can try !.
